config/routes.rb
Rails.application.routes.draw do
  resources :order
  resources :line_item
  resources :cart
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :countries
  resources :products
  resources :categories
  get 'shopperly/index'
  root 'shopperly#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_item, dependent: :destroy

  def add_products(products)
    current_item = line_item.find_by(products_id: products.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_item.build(products_id: products.id)
    end
    current_item
  end

  def total_price
    line_item.to_a.sum { |item| item.total_price }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /cart
  # GET /cart.json
  def index
    @cart = Cart.all
  end

  # GET /cart/1
  # GET /cart/1.json
  def show
  end

  # GET /cart/new
  def new
    @cart = Cart.new
  end

  # GET /cart/1/edit
  def edit
  end

  # POST /cart
  # POST /cart.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
  
  

  # PATCH/PUT /cart/1
  # PATCH/PUT /cart/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart/1
  # DELETE /cart/1.json
  
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully emptied.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
    
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', cart_index_path %>

app/views/cart/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/cart/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', cart_index_path %>

app/views/cart/show.html.erb
<section id="featured" class="featured">
<div class="container">
<div class="row">
<div class="col-lg-12">   
<h2>Your Cart</h2>

<hr />
<section class="section">
  <%= render(@cart.line_item) %>

  <div class="columns">
    <div class="column">
      
      <%= button_to "Place order", new_order_path, method: :get %>
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>

    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>


</div>
</div>
</div>
</section><!-- End Featured Section -->