config/routes.rb
Rails.application.routes.draw do
  resources :order
  resources :line_item
  resources :cart
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :countries
  resources :products
  resources :categories
  get 'shopperly/index'
  root 'shopperly#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :products, optional: true
  belongs_to :cart

  def total_price
    products.price.to_i * quantity.to_i
  end
end

app/controllers/line_item_controller.rb
class LineItemController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  # GET /line_item
  # GET /line_item.json
  def index
    @line_item = LineItem.all
  end

  # GET /line_item/1
  # GET /line_item/1.json
  def show
  end

  # GET /line_item/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_item/1/edit
  def edit
  end

  # POST /line_item
  # POST /line_item.json
  def create
    @products = Products.find(params[:products_id])
    @line_item = @cart.add_products(@products)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Product added to cart.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /line_item/1
  # PATCH/PUT /line_item/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_item/1
  # DELETE /line_item/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Item successfully removed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:products_id)
    end
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/views/line_item/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :products_id %>
    <%= form.text_field :products_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_item/_line_item.html.erb
<div class="columns align-items-center">
  <div class="column is-1">
        <strong>Quantity:</strong>
    <%= line_item.quantity %>
  </div>
 
  <div class="column is-9">
    <strong>Product:</strong> <%= line_item.products.name %>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <strong>Description:</strong><%= truncate(line_item.products.description, length: 140) %>
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4">Price:<%= number_to_currency(line_item.total_price) %></strong>
      </div>
    </div>
  </div>
</div>
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Keep Shopping', products_index_url, class: 'button is-warning' %>
</div>
<div class="has-text-right">
  <%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4" %>
</div>

<hr/ >

app/views/line_item/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_item_index_path %>

app/views/line_item/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Item</h1>

<table>
  <thead>
    <tr>
      <th>Products</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_item.each do |line_item| %>
      <tr>
        <td><%= line_item.products_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_item/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_item_index_path %>

app/views/line_item/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Products:</strong>
  <%= @line_item.products_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_item_index_path %>