config/routes.rb
Rails.application.routes.draw do
  resources :order
  resources :line_item
  resources :cart
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :countries
  resources :products
  resources :categories
  get 'shopperly/index'
  root 'shopperly#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_countries, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Countries.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @countries = Countries.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @countries = Countries.new(countries_params)

    respond_to do |format|
      if @countries.save
        format.html { redirect_to @countries, notice: 'Countries was successfully created.' }
        format.json { render :show, status: :created, location: @countries }
      else
        format.html { render :new }
        format.json { render json: @countries.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @countries.update(countries_params)
        format.html { redirect_to @countries, notice: 'Countries was successfully updated.' }
        format.json { render :show, status: :ok, location: @countries }
      else
        format.html { render :edit }
        format.json { render json: @countries.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @countries.destroy
    respond_to do |format|
      format.html { redirect_to countries_index_url, notice: 'Countries was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_countries
      @countries = Countries.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def countries_params
      params.require(:countries).permit(:name, :latitude, :longitude)
    end
    def admin_user
     redirect_to(shopperly_index_url, notice: 'You are not authorized to access this page') unless current_users.superadmin_role?  
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: countries, local: true) do |form| %>
  <% if countries.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(countries.errors.count, "error") %> prohibited this countries from being saved:</h2>

      <ul>
        <% countries.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Countries</h1>

<%= render 'form', countries: @countries %>

<%= link_to 'Show', @countries %> |
<%= link_to 'Back', countries_index_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |countries| %>
      <tr>
        <td><%= countries.name %></td>
        <td><%= countries.latitude %></td>
        <td><%= countries.longitude %></td>
        <td><%= link_to 'Show', countries %></td>
        <td><%= link_to 'Edit', edit_countries_path(countries) %></td>
        <td><%= link_to 'Destroy', countries, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Countries', new_countries_path %>

app/views/countries/new.html.erb
<h1>New Countries</h1>

<%= render 'form', countries: @countries %>

<%= link_to 'Back', countries_index_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @countries.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @countries.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @countries.longitude %>
</p>

<%= link_to 'Edit', edit_countries_path(@countries) %> |
<%= link_to 'Back', countries_index_path %>